Job filter should return empty list instead of error when id is not found #12
SilinPavel/grid-engine-api pull request #5
Opened 2022-05-20 13:09 UTC by NatusHonestus

Job filter should return empty list instead of error when id is not found #12

Bug during job filtration using ids was fixed
- If incorrect ids were provided, an exception will be thrown before filtration
- If a jobs wasn't found by provided id, an empty array will be returned insted of exception
- PR allows to filter jobs using ids properly

2022-05-24 09:01 UTC, Wedds requested changes

2022-05-24 09:01 UTC, Wedds commented on src/main/java/com/epam/grid/engine/provider/job/slurm/SlurmJobProvider.java
> +        if (result.getExitCode() != 0 && !result.getStdErr().toString().equals(jobIdNotFoundMessage)) {
Let's extract new conditional logic to a separate method (something named `isNotJobNotFoundError`)

2022-05-24 09:18 UTC, NatusHonestus commented on src/main/java/com/epam/grid/engine/provider/job/slurm/SlurmJobProvider.java
> +        if (result.getExitCode() != 0 && !result.getStdErr().toString().equals(jobIdNotFoundMessage)) {
done

2022-05-24 09:35 UTC, SilinPavel commented on src/main/java/com/epam/grid/engine/provider/job/slurm/SlurmJobProvider.java
> +    private boolean jobNotFoundByIdError(CommandResult result) {
move private method at the end of the file, after all public methods

2022-05-24 12:12 UTC, NatusHonestus commented on src/main/java/com/epam/grid/engine/provider/job/slurm/SlurmJobProvider.java
> +    private boolean jobNotFoundByIdError(CommandResult result) {
done

2022-05-24 13:33 UTC, Wedds requested changes

2022-05-24 13:33 UTC, Wedds commented on src/main/java/com/epam/grid/engine/provider/utils/slurm/job/SacctCommandParser.java
> +        if (jobFilter.idsIsNull() && jobFilter.getIds().size() > 0) {
This code seems to be a good candidate to be refactored with `Optional`, because you have
1. Nullability check
2. Filtering on size
3. Nested filtering on elements

So I think, this could be refactored:
```java
        Optional.ofNullable(filter)
            .map(/* getIds */)
            .filter(/* filter using CollectionUtils */)
            .stream()
            .flatMap(Collection::stream)
            .filter(/* filter id value */)
            .findFirst()
            .ifPresent(/* exception throwing */);
```

2022-05-24 14:01 UTC, NatusHonestus commented on src/main/java/com/epam/grid/engine/provider/utils/slurm/job/SacctCommandParser.java
> +        if (jobFilter.idsIsNull() && jobFilter.getIds().size() > 0) {
done

2022-05-25 07:55 UTC, Wedds approved these changes

2022-05-25 10:05 UTC, SilinPavel approved these changes

2022-05-25 10:06 UTC, merged